Module Constants
    Friend Const DefaultFontName = "Default"
    Friend Const DownKeyName = "Down"
    Friend Const EnterKeyName = "Enter"
    Friend Const EscapeKeyName = "Escape"
    Friend Const LeftKeyName = "Left"
    Friend Const RightKeyName = "Right"
    Friend Const SpaceKeyName = "Space"
    Friend Const UpKeyName = "Up"
    Friend Const CharacterStatusKeyName = "C"
    Friend Const ForageKeyName = "F"
    Friend Const HelpKeyName = "H"
    Friend Const InventoryKeyName = "I"
    Friend Const ZleepKeyName = "Z"
End Module
